[general]
updateChecksEnabled = false

[appearance]
mode = "automatic"

[borders]
enabled = true
width = 1.0

[gaps]
size = 4.0

[gaps.outer]
bottom = 0.0
left = 0.0
right = 0.0
top = 0.0

[niri]
visibleContainerCount = 2

[[monitorNiriOverrides]]
id = "3AE883DE-B85C-48F3-838C-45CE7841BB03"
monitorName = "DELL G3223Q"
monitorDisplayUUID = "E165D445-477D-4D2D-95E0-500E9940FE59"
visibleContainerCount = 3

[[monitorNiriOverrides]]
id = "288ABB9D-D8C5-42A0-9147-1E19174FAA4F"
monitorName = "Built-in Retina Display"
monitorDisplayUUID = "37D8832A-2D66-02CA-B9F7-8F30A301B230"
visibleContainerCount = 2

[hiddenBar]
enabled = true
hiddenBundleIDs = []
rehideIntervalSeconds = 5.0

[mouseWarp]
constrainToArrangement = false
enabled = true
margin = 1

[statusBar]
showAppNames = false
showWorkspaceName = false
useWorkspaceId = false

[workspaceBar]
backgroundOpacity = 0.1
deduplicateAppIcons = false
enabled = true
excludedBundleIDs = []
height = 24.0
hideEmptyWorkspaces = false
notchActiveZoneWidth = 180.0
notchMode = "moveBelowMenuBar"
position = "overlappingMenuBar"
reserveLayoutSpace = false
revealHoldMilliseconds = 200.0
revealModifier = "off"
showFloatingWindows = false
showLabels = true
systemStatsButton = false
windowLevel = "popup"
xOffset = 0.0
yOffset = 0.0

[[hotkeys]]
binding = "Option+Tab"
id = "workspaceBackAndForth"

[[hotkeys]]
binding = "Option+Right Bracket"
id = "switchWorkspace.next"

[[hotkeys]]
binding = "Option+Left Bracket"
id = "switchWorkspace.previous"

[[hotkeys]]
binding = "Option+H"
id = "focus.left"

[[hotkeys]]
binding = "Option+J"
id = "focus.down"

[[hotkeys]]
binding = "Option+K"
id = "focus.up"

[[hotkeys]]
binding = "Option+L"
id = "focus.right"

[[hotkeys]]
binding = "Control+Option+Tab"
id = "focusPrevious"

[[hotkeys]]
binding = "Option+Shift+Left Bracket"
id = "moveWindowToWorkspaceUp"

[[hotkeys]]
binding = "Option+Shift+Right Bracket"
id = "moveWindowToWorkspaceDown"

[[hotkeys]]
binding = "Option+Shift+H"
id = "move.left"

[[hotkeys]]
binding = "Option+Shift+J"
id = "move.down"

[[hotkeys]]
binding = "Option+Shift+K"
id = "move.up"

[[hotkeys]]
binding = "Option+Shift+L"
id = "move.right"

[[hotkeys]]
binding = "Hyper+F"
id = "moveWindowToMonitor.left"

[[hotkeys]]
binding = "Hyper+G"
id = "moveWindowToMonitor.right"

[[hotkeys]]
binding = "Option+Equal"
id = "cycleSizeForward"

[[hotkeys]]
binding = "Option+Minus"
id = "cycleSizeBackward"

[[hotkeys]]
binding = "Hyper+L"
id = "toggleWorkspaceLayout"

[[hotkeys]]
binding = "Unassigned"
id = "toggleFullscreen"

[[hotkeys]]
binding = "Unassigned"
id = "setContainerPrimarySpan.decrease10Percent"

[[hotkeys]]
binding = "Unassigned"
id = "setContainerPrimarySpan.increase10Percent"
