name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.301.0
      with:
        ruby-version: 'ruby'
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake test
